package com.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.8
 * 2013-06-17T17:31:57.672+08:00
 * Generated source version: 2.6.8
 */
@WebService(targetNamespace = "http://service.cxf.com/", name = "HelloWorldImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldImpl {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://service.cxf.com/", className = "com.cxf.client.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.client.SayHelloResponse")
    public java.lang.String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    java.lang.String arg0
    );

    @RequestWrapper(localName = "annexTransportation", targetNamespace = "http://service.cxf.com/", className = "com.cxf.client.AnnexTransportation")
    @WebMethod
    @ResponseWrapper(localName = "annexTransportationResponse", targetNamespace = "http://service.cxf.com/", className = "com.cxf.client.AnnexTransportationResponse")
    public void annexTransportation(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.cxf.client.Annex arg0
    );
}
